### ISSUE TITLE
Fee Estimation fails

### ISSUE THREAD

**Issue by lclc** [Feathercoin-Foundation/electrum-ftc#1]
The fee estimation is always 0 since there aren't yet many transactions on the Feathercoin blockchain:

From the log:
`[profiler] estimated_size 0.0000`

Seems that this is a problem for the Electrum client.

Feathercoin Core sets a fix fee of 0.01 FTC. Easiest for us would be to do the same for now.

**Comment by lclc** [comment]
We can hard configure the estimate and relay fee on the ElectrumX server to 1 Satoshi / Byte with
```
    ESTIMATE_FEE = 0.00001
    RELAY_FEE = 0.00001
    DAEMON = daemon.FakeEstimateFeeDaemon
```

This is currently set for electrumx-ch-1.feathercoin.ch.   

electrumx-de-2.feathercoin.ch is still on dynamic  calculated fees.


But we'd also have to adjust the relay fee in Feathercoin Core. @bushstar what's your opinion on this?
Since the blocks are empty it would make FTC cheaper to use.

**Comment by lclc** [comment]
More information on the relay fee can be found here: https://bitcoin.org/en/release/v0.11.0#transaction-flooding

**Comment by Bushstar** [comment]
This is the fee adjustment commit in FTC 0.13 based on 0.9, I'm sure it is higher than I remember.

https://github.com/FeatherCoin/Feathercoin/commit/aa0c60bbd88b78f7ced56eb829a49b7022576501

DEFAULT_MIN_RELAY_TX_FEE = 1000000;
DEFAULT_TRANSACTION_MINFEE = 1000000;
DEFAULT_FALLBACK_FEE = 2000000;

In practice this works out more like 2,000 Sats per byte.

**Comment by lclc** [comment]
Hm, why do we have higher minimum fees than Bitcoin (Core) ?

Maybe we could lower it again for 0.16 ? Either leave it as it is in Bitcoin Core or put it even lower.

**Comment by Bushstar** [comment]
It is higher as our value is much lower, even with these "high" fees you are looking at an average of roughly $0.002 per TX, it is still a lot cheaper to use Feathercoin than other major currencies. I sent a TX on Bitcoin the other day for 500 Sats, that's $0.04.

TX fees are there to protect the network against spam, too low and we make that attack vector more affordable. At an average of 20 times cheaper than Bitcoin we are not in a bad position but if our price moves radically we may be put into one.

At most I'd opt to go down 10 fold in the 0.16 release to 200 Sats per byte which will work out to roughly $0.0002 per TX.

**Comment by lclc** [comment]
Ok. Makes sense. I've set a minimum transaction fee too to work around this.
