### ISSUE TITLE
Version number is missing

### ISSUE THREAD

**Issue by rmrm-rami** [Feathercoin-Foundation/electrum-ftc#103]
## Expected Behavior
When clicking on Help -> About (and also on the title bar at the top), you should see the version number, which doesn't appear now:

![image](https://user-images.githubusercontent.com/37974898/41780819-1953ded2-7636-11e8-85fa-2f2e6a86de58.png)

## Current Behavior
Doesn't show

## Possible Solution
-
## Context
Wanted to check if I have the current version 3.1.3.1

## Your Environment
* Version used: 3.1.3.1
* Operating System and version: Windows 10

**Comment by toxeus** [comment]
I can confirm this bug being present on Windows.

**Comment by toxeus** [comment]
This is fundamentally an I/O bug in wine. It has been fixed using a workaround on the `3.2.X` branch.
