### ISSUE TITLE
My wallet aren't connecting  

### ISSUE THREAD

**Issue by dedetuga** [Feathercoin-Foundation/electrum-ftc#114]
Hi
 I updated my wallet to (because the old one are not connecting anymore) last wallet from git and run it, 
but always says not connected, 
how can i solve this?

* Version used: eletrum-ftc 3.3.8.0
* Operating System and version: ubuntu 20.04LTS

**Comment by HasseM** [comment]
Same problem here on Win10....

**Comment by oliverjanda** [comment]
Same problem here on Win10....

**Comment by dedetuga** [comment]
Solved!!!!

Just connect your wallet to `p2pool.neoscrypt.de`

#115
