### ISSUE TITLE
The donate menu point to a trezarcoin address

### ISSUE THREAD

**Issue by dufflesterny** [Feathercoin-Foundation/electrum-ftc#13]
733zxJR6W5K6nVWP3F36rtiwzLqWxe6wkb

description: donation for electrumxftc.trezarcoin.com

doesn't look right.

**Comment by dufflesterny** [comment]
Now it looks okay ...
Due to auto-server load?

6mkz4QfQc1PKWbZidhfEDhGmMnSrCqv8HJ
donation for electrumx-ch-1.feathercoin.ch

**Comment by lclc** [comment]
Hi, can you provide us with some more information regarding the problem ?

The wallet automatically connects to a random server by default. But you can change that in the settings if you want.

The donation goes to the server operator.

electrumxftc.trezarcoin.com is the domain name of one of our server operators. There are servers run by the Foundation and various community members.  It is a Feathercoin Electrum Server even though it has trezarcoin in the name.

**Comment by dufflesterny** [comment]
Hi, with the domain containing trezarcoin.com it was a bit suspicious to me. Now i understand that this is not a wallet issue, so i just closed the issue.
