### ISSUE TITLE
No Ctrl+C / Cmd+C possible for receiving address

### ISSUE THREAD

**Issue by rmrm-rami** [Feathercoin-Foundation/electrum-ftc#15]
It's not possible to copy the generated receiving addresses via Ctrl/Cmd+C, copying only works by clicking the button at the very right.

**Comment by toxeus** [comment]
I can confirm this.

**Comment by toxeus** [comment]
On Linux it doesn't work either using ctrl+c but it works using select and mid-mouse-click. Seems to me that this was disabled deliberately.

**Comment by toxeus** [comment]
[This](https://github.com/Feathercoin-Foundation/electrum-ftc/blob/9bfa9c69428935e9bce7430415583b6444d7d9df/gui/qt/main_window.py#L769) is the line that disables `ctrl-c`.

From the [documentation](https://doc.qt.io/qt-5/qwidget.html#focusPolicy-prop):

>  You must enable keyboard focus for a widget if it processes keyboard events.

So the question is if we want to enable `ctrl-c`? We already know that some users find it confusing. Is there a downside to allow `ctrl-c`? Addresses have a hash checksum so if a user partially selects the address and copy&pastes it then it should fail and no coins are lost then.

**Comment by toxeus** [comment]
The [commit](https://github.com/spesmilo/electrum/commit/7148e1a28718f77ff1654ae15a605924256ff3be) message from upstream doesn't explain any rationale.

**Comment by rogerdarin** [comment]
I've come across websites that automatically select the entire key when you click on a part of it, that would avoid accidental partial copy/paste. 

Having said that, even without that I believe the checksum check provides sufficient safety.

**Comment by toxeus** [comment]
We've asked upstream directly. They aren't aware that `Qt.NoFocus` disables ctrl-c/ctrl-v. On MacOS `Qt.NoFocus` doesn't seem to affect ctrl-c/ctrl-v. But it does so on Windows and Linux. Fix incoming.
