### ISSUE TITLE
Error: Cannot load wallet: ('unknown hardware type', 'digitalbitbox')

### ISSUE THREAD

**Issue by aciddude** [Feathercoin-Foundation/electrum-ftc#19]
Hi Guys, 

1 - start new electrum portable 3.0.6.3 

2 - create new wallet  "defaul_wallet_1"

3 - choose standard wallet 

4 - use hardware device 

5 - digitalbitbox selected, initiallized

6 - enter digitalbitbox password

7 - load wallet from SD card

8 - select feathercoin backup 

9 - Do not pair

10 - it shows the derivation  " m/44'/8'/0' "

11 - yay! electrum opens and I can see my wallet. 

12 -   close the wallet and reopen   and I get the below error. 

Error
—-------------------------
Cannot load wallet:
('unknown hardware type', 'digitalbitbox')
—--------------

if I delete the wallet it creates in the data dir and I reload it from my digitalbitbox using the above steps I can access it again and send feathercoins etc..  when I close it and try to open..I get the above error. 

This is on Electrum 3.0.6.3  Windows 10

**Comment by toxeus** [comment]
[fixed](https://github.com/Feathercoin-Foundation/electrum-ftc/commit/61b10ab9577c557584e8b7634e826a3423517e0d)
