### ISSUE TITLE
Add https://chainz.cryptoid.info/ftc/ as default block explorer

### ISSUE THREAD

**Issue by rmrm-rami** [Feathercoin-Foundation/electrum-ftc#22]
Or at least make it an option in the Preferences->Appearance section:

![image](https://user-images.githubusercontent.com/37974898/40046728-f8ff402a-582d-11e8-951b-dc33dab1cff9.png)

**Comment by ghost** [comment]
As my commit got merged two months ago and `https://chainz.cryptoid.info/ftc/` is now an option, we may close this issue.

**Comment by lclc** [comment]
Thanks!
