### ISSUE TITLE
Contacts Tab details are not getting updated when we restore a wallet using "I already have a seed option"

### ISSUE THREAD

**Issue by Anilkumar18** [Feathercoin-Foundation/electrum-ftc#29]
When we try to create a wallet with a seed of existing wallet , all the details mentioned in the existing wallet should be copied/restored to the newly created wallet also

Currently , Contacts Tab details are not getting updated when we restore a wallet using "I already have a seed option"

Steps to Replicate

- Select File ->New/Restore in Electrum FTC
- Give a wallet Name and click on Next
- Select Standard wallet and click Next
- Select "I already have a seed" option and click Next
- In the Enter seed window type in the seed of a preexisting wallet which has contacts details in it.
- The copy of the original wallet would be made with a different wallet name and all the details such as coins, addresses are restored from the original wallet but the contact tab alone doesnt display the details from the original wallet.

Note : Exists in Bitcoin also

**Comment by lclc** [comment]
That's technically not possible to restore from a seed.
