### ISSUE TITLE
Fix UI style

### ISSUE THREAD

**Issue by lclc** [Feathercoin-Foundation/electrum-ftc#3]
The binaries built by us for Windows and OSX look ugly. Seems to be missing the style files.

**Comment by toxeus** [comment]
Maybe [this](https://github.com/spesmilo/electrum/blob/7e6fba0513b6a8db0a0546e8184f7d7a66008585/contrib/build-osx/osx.spec#L47-L48) helps?

**Comment by lclc** [comment]
Thanks @toxeus, that fixed it ! :)
