### ISSUE TITLE
Max Button in Send tab should always be active

### ISSUE THREAD

**Issue by Anilkumar18** [Feathercoin-Foundation/electrum-ftc#40]
Max   button for the Amount column should always be active

Steps to Replicate
- Open a   wallet     
- Click on send tab    
- Click on Max button to view the amount in the amount textbox that can be  transfered to the required address     
- Now click inside the amount textbox and edit the amount manually, immediately the MAX button is disabled     
- Now if the user changes his mind and wants to see the max amount that can be sent to the address , then there is no way to do it

Note : Issue exists in Bitcoin also

**Comment by lclc** [comment]
Seems to be a copy of #32
