### ISSUE TITLE
Receive Tab -> Request Amount Field -> If the request amount field is left blank and saved then it should throw an error message stating an "No coins"

### ISSUE THREAD

**Issue by Anilkumar18** [Feathercoin-Foundation/electrum-ftc#57]
## Expected Behavior
Receive Tab -> Request Amount Field -> If the request amount field is left blank and saved then it should throw an error message stating an "No coins"

## Current Behavior
Receive Tab -> Request Amount Field -> If the request amount field is left blank and saved then the request gets saved without the Amount

## Steps to Reproduce
1.Open a wallet
2.Click on Receive tab
3.Clicking on save without entering a request amount
4.The details gets saved in the request list
5.An error msg should be displayed saying"Enter a valid amount" or the Save button should be disabled untill all required fields are filled.

## Your Environment
* Version used: Electrum FTC 3.0.6.5
* Operating System and version: Windows 10

![amt_field](https://user-images.githubusercontent.com/32846534/40698901-344ea1da-63ef-11e8-9256-a0c25bde9a55.png)

**Comment by lclc** [comment]
This is not a bug but a feature ;)

There is a use case for saving a Receive request without an amount:
I, as an non-profit organisation give you a unique address generated to donate to. There is no minimum amount I expect from you therefore I don't put an amount in there. I just know afterwards that all the money that goes to that address comes from you.
