### ISSUE TITLE
Addresses Tab -> Encrypt/Decrypt -> The 'encrypted message' field should be noneditable

### ISSUE THREAD

**Issue by Anilkumar18** [Feathercoin-Foundation/electrum-ftc#63]
## Expected Behavior
Addresses Tab -> Encrypt/Decrypt -> The 'encrypted message' field should be noneditable

## Current Behavior
Addresses Tab -> Encrypt/Decrypt -> The 'encrypted message' field is noneditable

## Steps to Reproduce
1.Open a wallet
2.Go to addresses tab,right click on a particular address and select encrypt/decrypt in the pop up
3.In the encrypt/decrypt window enter text in message text field  and click on Encrypt
4.Encrypted message is automatically generated and displayed in the field
5.The field should be noneditable and user should only be allowed to copy from it

## Context
If the user edits/deletes the message unknowingly, then he would have to decrypt it again

## Your Environment

* Version used: Electrum FTC 3.0.6.5
* Operating System and version: Windows 10

Note : Issue exists in Bitcoin also

**Comment by lclc** [comment]
Same as in https://github.com/Feathercoin-Foundation/electrum-ftc/issues/61.

I may want to hand you an encrypted text that you want to enter there. E.g. you get from me the following:
Public Key: 0207d403a4c93e7ad8e9edad9e6f90059d240993579ae7524a8e43720043c15e05
Encrypted: QklFMQPVCfkvZiQWNrJ5CmxP4ypxNI6CF1/4WrL9Emc0qnfYfWdiuLwqhV0W9/dsnepKxB8EAVPsbz+eLVtZ/L6+mNp0aV7//2rv8aEniS5Q/tpvGqhrTu/jF7duWFCOCGiQ2aU=
